chat/urls.py
from django.urls import path
from . import views


app_name = "chat"  # URL 해석시 사용할 namespace 이름

# "/chat/"으로 시작하는 URL 패턴
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

minesweeper/urls.py
from django.urls import path
from . import views


app_name = "minesweeper"  # URL 해석시 사용할 namespace 이름

urlpatterns = [
    path("", views.index, name="index"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),    # 관리자 페이지를 위한 URL 매핑
    path('', include('minesweeper.urls')),    # 'minesweeper' 앱의 URL들을 포함하기 위한 URL 매핑
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),    # 미디어 파일 요청을 처리하기 위한 URL 패턴
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),   # 정적 파일 요청을 처리하기 위한 URL 패턴
)

minesweeper/models.py
from django.db import models

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question
import os

from .models import Choice, Question


# /chat/
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = { "latest_question_list": latest_question_list }
    return render(request, "chat/index.html", context)


# /chat/<int:question_id>/
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "chat/detail.html", {'question': question})


# /chat/<int:question_id>/results/
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "chat/results.html", {"question": question})


# /chat/<int:question_id>/vote/
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "chat/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("chat:results", args=(question.id,)))

minesweeper/views.py
from django.shortcuts import render


# /minesweeper/
def index(request):
    x_len, y_len = 33, 17    # 가로,세로 길이(29, 15)
    polygons = []
    for y in range(y_len):
        for x in range(x_len - (y % 2)):
            points = "{},{} {},{} {},{} {},{} {},{} {},{}".format(
                16 + 7 * (y % 2) + 14 * x, 1 + 12 * y,
                23 + 7 * (y % 2) + 14 * x, 5 + 12 * y,
                23 + 7 * (y % 2) + 14 * x, 13 + 12 * y,
                16 + 7 * (y % 2) + 14 * x, 17 + 12 * y,
                9 + 7 * (y % 2) + 14 * x, 13 + 12 * y,
                9 + 7 * (y % 2) + 14 * x, 5 + 12 * y
            )
            polygon_id = f"{x}-{y}"
            polygons.append({"points":points, "polygon_id":polygon_id})
    context = { 
               "polygons": polygons,
               "svg_id": f"{x_len}-{y_len}",
    }
    return render(request, "minesweeper/index.html", context)

chat/templates/chat/detail.html
<form action="{% url 'chat:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block title %}Wilson{% endblock  %}

{% block main %}
    <div class="contianer-fluid">
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <input type="text" name="message">
                    <input type="submit" value="Send">
                </form>
            </div>
            <div class="col">
                {% if latest_question_list %}
                <ul>
                    {% for question in latest_question_list %}
                        <li><a href={% url "chat:detail" question.id %}>{{ question.question_text }}</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                <p>No polls are available.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock  %}

chat/templates/chat/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'chat:detail' question.id %}">Vote again?</a>

minesweeper/templates/minesweeper/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="ko" data-bs-theme="auto">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="육각지뢰찾기입니다. 벌을 피해 벌집 내 모든 꿀을 채취해보세요!">
    <title>{% block title %}{% endblock  %}</title>

    {% block link %}{% endblock %}
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'minesweeper/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'minesweeper/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static  'minesweeper/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'minesweeper/images/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'minesweeper/images/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{% static 'minesweeper/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'minesweeper/css/navbars.css' %}">
    <script src="{% static 'minesweeper/js/color-modes.js' %}"></script>

    <!-- Bootstrap Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- SVG 스프라이트 컨테이너: 화면에 직접 표시되지 않습니다. -->
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
            <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
            <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
            <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
            <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
        </symbol>
    </svg>

    <!-- 테마(dark, light, auto) 변경 기능을 가진 드롭다운 버튼을 생성 -->
    <div class="btn-group dropup position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
                id="bd-theme"
                type="button"
                aria-expanded="false"
                data-bs-toggle="dropdown"
                aria-label="Toggle theme (auto)">
          <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
          <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
              Light
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
              Dark
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
              Auto
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
        </ul>
    </div>

    <main>
        <div class="container">

            <nav class="navbar navbar-expand-lg rounded" style="background-color: sienna;" aria-label="Thirteenth navbar example">
                <div class="container-fluid d-flex justify-content-between">
                    <!-- 왼쪽 측면에 배치 -->
                    <a href="javascript:location.reload()" class="disabled" aria-disabled="true">
                        <img src="{% static 'minesweeper/images/BeeCarefule.svg' %}" alt="Logo" style="height: 40px;">
                    </a>
                    <div class="collapse navbar-collapse">
                        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                            <li class="nav-item">
                                <a class="nav-link disabled" aria-disabled="true">{% translate "지뢰찾기 게임" %}</a>
                            </li>
                        </ul>
                    </div>
                    <!-- 오른쪽 측면에 배치 -->
                    <div class="btn-group d-lg-flex justify-content-lg-end" role="group"  style="padding-left: 100px;">
                        <button id="navbarDropdownMenuLink" 
                                type="button" 
                                class="btn btn-light btn-sm dropdown-toggle" 
                                data-bs-toggle="dropdown" 
                                aria-expanded="false" 
                                style="font-weight: 600;">
                            <!-- 자바스크립트로 설정될 텍스트 -->
                        </button>
                        <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="/en/">{% translate "English" %}</a></li>
                            <li><a class="dropdown-item" href="/ja/">{% translate "Japanese" %}</a></li>
                            <li><a class="dropdown-item" href="/ko/">{% translate "Korean" %}</a></li>
                            <li><a class="dropdown-item" href="/es/">{% translate "Spanish" %}</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

            {% block main %}{% endblock  %}

        </div>
    </main>
    
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var currentPath = window.location.pathname;
            // 버튼의 텍스트 설정
            var languageButton = document.getElementById('navbarDropdownMenuLink');
            if (currentPath.startsWith('/ko/')) {
                languageButton.textContent = '한국어';
            } else if (currentPath.startsWith('/en/')) {
                languageButton.textContent = 'English';
            } else if (currentPath.startsWith('/es/')) {
                languageButton.textContent = 'Español';
            } else if (currentPath.startsWith('/ja/')) {
                languageButton.textContent = '日本語';
            }
        });
    </script>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

minesweeper/templates/minesweeper/index.html
{% extends "minesweeper/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}BeeCareful{% endblock  %}
{% block link %}
<link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700&display=swap" rel="stylesheet">
{% endblock  %}

{% block main %}
<div class="row text-center justify-content-center px-5 fs-4 d-none d-md-flex align-items-center" style="padding-bottom: 6px;">
    <div class="col-2" style="user-select: none;">
        <span id="flagCount">🚩0</span>
    </div>
    <div class="col-2" id="stopwatch" style="user-select: none;">00:00</div>
    <div class="col-2">
        <!-- 게임 리셋 버튼 -->
        <button id="resetButton" type="button" class="btn btn-secondary" style="padding-left: 10px; font-size: 15px">
            🔄RESTART
        </button>
    </div>
</div>

<div class="row align-items-center">
    <div class="col d-none d-xxl-block ps-0">
        <div class="card text-center border-secondary-subtle mx-0" style="background-color: gold;">
            <h6 class="card-header text-white" style="background-color: sienna;">{% translate "최고 기록" %}</h6>
            <div class="card-body text-dark">
                <span id="bestTime" class="record">00:00</span> 
            </div>
        </div>
    </div>
    <div class="col px-0">
        <svg id="board{{ svg_id }}" width="1020" height="450" viewBox="0 0 480 210">  <!-- 한 변의 길이는 8(7)으로 -->
            {% for polygon in polygons %}
            <polygon points="{{ polygon.points }}" id="{{ polygon.polygon_id }}" class='hover'/>
            {% endfor %}
        </svg>
    </div>
    <div class="col d-none d-xxl-block pe-0">
        <div class="card text-center border-secondary-subtle mx-0" style="background-color: gold;">
            <h6 class="card-header text-white" style="background-color: sienna;">{% translate "평균 기록" %}</h6>
            <div class="card-body text-dark">
                <span id="averageTime" class="record">00:00</span> 
            </div>
        </div>
    </div>
</div>

<h3 class="text-center" id="guide-message" style="padding-top: 14px;">
    {% translate "벌을 피해 꿀을 훔치세요!" %}
</h3>

<!-- 스크립트 파일 가져오기 -->
<script src="{% static 'minesweeper/js/game.js' %}"></script>
{% endblock  %}